TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
TWILIO_FROM_NUMBER ="TWILIO_FROM_NUMBER"
EMERGENCY_CONTACT = "EMERGENCY_CONTACT"
GROQ_API_KEY = "GROQ_API_KEY"

